openapi: 3.0.1
info:
  title: OpenAPI definition
  description: API for calculating pricing and managing sample data, interacting with Salesforce via AppLink.
  version: v0
servers:
- url: http://localhost:5000
  description: Local development server
tags:
- name: Pricing Engine
  description: Leverage dynamic pricing calculation logic and rules to calculate pricing
    information in the form of Quotes.
- name: Sample Data
  description: Sample data management endpoints
paths:
  /api/executebatch:
    post:
      tags:
      - Pricing Engine
      summary: Start batch processing for Quote generation
      description: Calculate pricing and generate quotes from Opportunities queried
        using the SOQL WHERE clause.
      operationId: executeBatch
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchExecutionRequest"
        required: true
      responses:
        "202":
          description: Job accepted for processing
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/JobResponse"
  /api/data/delete:
    post:
      tags:
      - Sample Data
      summary: Submit Sample Data Deletion Job
      description: Starts a job to delete generate Quotes
      operationId: datadelete
      responses:
        "202":
          description: Data operation job accepted
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/JobResponse"
  /api/data/create:
    post:
      tags:
      - Sample Data
      summary: Submit Sample Data Creation Job
      description: Starts a job to create a large amount of Opportunity records.
      operationId: datacreate
      responses:
        "202":
          description: Data operation job accepted
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/JobResponse"
components:
  schemas:
    BatchExecutionRequest:
      type: object
      properties:
        soqlWhereClause:
          type: string
          description: A SOQL WHERE clause for filtering opportunities
      description: "Request to execute a batch process, includes a SOQL WHERE clause to extract product information"
    JobResponse:
      type: object
      properties:
        jobId:
          type: string
          format: uuid
          description: Unique job ID for tracking the worker process
      description: Response includes the unique job ID processing the request.
